### ISSUE TITLE
Website cherrypy.org is down since few days

### ISSUE THREAD

**Issue by brainbytes42** [cherrypy/cherrypy.github.io#12]
Hello,

although I assume, you are aware of it and this reporting is unnecessary - if not, here you are. ;-)

cherrypy.org seems to be down since a few days. And it's not just for me: https://downforeveryoneorjustme.com/cherrypy.org.

Unfortunately, the docs are all there... (and as they are linked from this github-site, I file the issue here...)

**Comment by webknjaz** [comment]
Yep, I hope it's temporary. I've posted the working links in the tracking issue: https://github.com/cherrypy/cherrypy/issues/1872#issuecomment-873900823.

**Comment by brainbytes42** [comment]
Thanks for the links! I hadn't found that thread. 

Good luck with the domain!
